import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lisztian' at '1/23/18 1:41 PM' with Gradle 3.0
 *
 * @author lisztian, @date 1/23/18 1:41 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        }
}
